---
version: 2
updates:
  # Enable version updates for Python Poetry
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop" # Default branch for PRs
    commit-message:
      prefix: "chore(deps)"
      include: "scope" 