---
private_app_list:
  - id: "TA-tesla-data"
    url: "github://livehybrid/TA-tesla-data"
    version: "v1.1.1"
  - id: "splunk_app_scdeploy"
    url: "github://livehybrid/splunk_app_scdeploy"
    version: "v1.3.1"
    #api_token: "secrethere"
