---
splunk_cloud_default_apps_list:
  - "000-self-service"
  - "075-cloudworks"
  - "100-cloudworks-wlm"
  - "100-whisper"
  - "100-whisper-common"
  - "100-whisper-searchhead"
  - "alert_logevent"
  - "alert_webhook"
  - "appsbrowser"
  - "cloud-app-readiness"
  - "cloud_administration"
  - "data_manager"
  - "dmc"
  - "dynamic-data-self-storage-app"
  - "introspection_generator_addon"
  - "journald_input"
  - "launcher"
  - "learned"
  - "legacy"
  - "prometheus"
  - "python_upgrade_readiness_app"
  - "sample_app"
  - "scsaudit"
  - "search"
  - "search_artifacts_helper"
  - "splunk-dashboard-studio"
  - "splunk_gdi"
  - "splunk_httpinput"
  - "splunk_instance_monitoring"
  - "splunk_instrumentation"
  - "splunk_internal_metrics"
  - "splunk_metrics_workspace"
  - "splunk_rapid_diag"
  - "splunk_secure_gateway"
  - "splunkclouduf"
  - "tos"
