name: deploy index config
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "inventory/host_vars/*/index_config.yml"

concurrency:
  group: ${{ github.workflow }}

jobs:
  ansible:
    name: deploy index config
    uses: ./.github/workflows/ansible-playbook.yml
    with:
      ansible_playbook: cloud_index_config.yml
      ansible_inventory: inventory
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
